# app/services/__init__.py

# This makes the 'services' directory a Python package.
# You can import service modules from here if needed directly
# or services can be used by routes directly.

# from .file_service import ...
# from .email_service import ...
# from .cost_service import ...
# from .thumbnail_service import ...

# print("services package initialized.") # Debug 