"""Initial migration; create job table

Revision ID: 206a05314de9
Revises: 
Create Date: 2025-05-15 13:59:10.986279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206a05314de9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('student_email', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('printer', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('material', sa.String(length=32), nullable=True),
    sa.Column('weight_g', sa.Float(), nullable=True),
    sa.Column('time_min', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('student_confirmed', sa.Boolean(), nullable=False),
    sa.Column('student_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirm_token', sa.String(length=128), nullable=True),
    sa.Column('confirm_token_expires', sa.DateTime(), nullable=True),
    sa.Column('reject_reasons', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_by', sa.String(length=50), nullable=True),
    sa.Column('discipline', sa.String(length=100), nullable=True),
    sa.Column('class_number', sa.String(length=50), nullable=True),
    sa.Column('scaled_correctly', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_minimum_charge', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirm_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
